CREATE USER IF NOT EXISTS 'local'@'%' IDENTIFIED BY 'local';
ALTER USER 'local'@'%' IDENTIFIED BY 'local';
GRANT ALL PRIVILEGES ON *.* TO 'local'@'%' WITH GRANT OPTION;

CREATE DATABASE IF NOT EXISTS baseapp;